'use strict';
const message=document.querySelector('[data-auth-message]');
const setMessage=text=>{if(message)message.textContent=text;};
async function api(path,options={}){const response=await fetch('/api/auth/'+path,{credentials:'same-origin',cache:'no-store',...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'認証に失敗しました');return data;}
const json=body=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
document.querySelector('[data-login-form]')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const button=form.querySelector('[data-auth-submit]');button.disabled=true;try{await api('login',json({username:form.elements.namedItem('username').value,password:form.elements.namedItem('password').value}));location.replace('/index.html');}catch(error){setMessage(error.message);button.disabled=false;}});
document.querySelector('[data-register-form]')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const button=form.querySelector('[data-auth-submit]');button.disabled=true;try{await api('signup',json({username:form.elements.namedItem('username').value,displayName:form.elements.namedItem('displayName').value,password:form.elements.namedItem('password').value,acceptTerms:form.elements.namedItem('acceptTerms').checked}));location.replace('/index.html');}catch(error){setMessage(error.message);button.disabled=false;}});
if(document.body.dataset.auth==='required')api('me').then(user=>{document.querySelectorAll('[data-user-name]').forEach(node=>node.textContent=user.displayName);document.dispatchEvent(new CustomEvent('catHubAuthReady',{detail:user}));if(document.body.dataset.admin==='required')fetch('/api/admin/status',{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);document.dispatchEvent(new CustomEvent('catHubAdminReady',{detail:data}));}).catch(error=>setMessage(error.message));}).catch(()=>location.replace('/login.html'));
document.querySelectorAll('[data-logout]').forEach(button=>button.addEventListener('click',async event=>{event.preventDefault();await api('logout',{method:'POST'});location.replace('/login.html');}));
