'use strict';
const gamesNode=document.querySelector('[data-games]'),statusNode=document.querySelector('[data-game-status]');
let games=[],filter='all';
function draw(){gamesNode.replaceChildren();const visible=filter==='favorites'?games.filter(game=>game.favorite):games;if(!visible.length){const empty=document.createElement('p');empty.textContent='該当するゲームがありません。';gamesNode.append(empty);return;}
 visible.forEach(game=>{const card=document.createElement('article');card.className='card';const category=document.createElement('div');category.className='eyebrow';category.textContent=game.category+' / '+game.platform;const title=document.createElement('h2');title.textContent=game.title;const desc=document.createElement('p');desc.textContent=game.description;const author=document.createElement('p');author.textContent='作者: '+game.author;const actions=document.createElement('div');actions.className='actions';const open=document.createElement('a');open.className='btn';open.href=game.url;open.textContent='詳細・プレイ';if(!game.url.startsWith('/')){open.target='_blank';open.rel='noopener noreferrer';}const fav=document.createElement('button');fav.className='btn ghost';fav.textContent=game.favorite?'お気に入り解除':'お気に入り追加';fav.addEventListener('click',async()=>{const response=await fetch('/api/games/'+game.id+'/favorite',{method:game.favorite?'DELETE':'POST'});if(!response.ok){statusNode.textContent='更新できませんでした。';return;}game.favorite=!game.favorite;draw();});actions.append(open,fav);card.append(category,title,desc,author,actions);gamesNode.append(card);});}
async function load(){const form=document.querySelector('[data-game-search]'),params=new URLSearchParams(new FormData(form));statusNode.textContent='読み込み中…';try{const response=await fetch('/api/games?'+params,{cache:'no-store'});if(!response.ok)throw new Error('ゲームを取得できません');games=await response.json();statusNode.textContent='';draw();}catch(error){statusNode.textContent=error.message;}}
document.querySelector('[data-game-search]').addEventListener('submit',event=>{event.preventDefault();load();});
document.querySelectorAll('[data-game-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.gameFilter;document.querySelectorAll('[data-game-filter]').forEach(x=>x.classList.toggle('active',x===button));draw();}));
document.addEventListener('catHubAuthReady',load);
